### ISSUE TITLE
Add stylecop.analyzers?

### ISSUE THREAD

**Issue by JohanLarsson** [JwanKhalaf/LyricsBee.Api#3]
For consistent formatting of all the things. Adding it early will prevent noisy diffs fixing formatting in the future.

https://www.nuget.org/packages/StyleCop.Analyzers/

**Comment by JwanKhalaf** [comment]
Good shout, I'll add it now.

**Comment by JwanKhalaf** [comment]
Added StyleCop as part of this PR: https://github.com/JwanKhalaf/LyricsBee.Api/pull/4
